services:
  server:
    build: ./packages/server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://172.17.0.1:27017/fcm-push
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  admin-panel:
    build: ./packages/admin-panel
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - SERVER_API_URL=http://server:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
