services:
  server:
    build: ./packages/server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://172.17.0.1:27017/fcm-push
      - FIREBASE_PRIVATE_KEY_B64=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFprajBZa3YwcldoczYKTzRGdEQwbGZ4SWdETEpTNTRsWGdscTBpbHZicG04eUxHWEhScVF3aGVEM09nd3VkZW0vNnFmdTJzVWI2Zm40TQouLi5yZXN0X29mX2tleS4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      - FIREBASE_PROJECT_ID=gen-lang-client-0462704292
      - FIREBASE_CLIENT_EMAIL=fcm-636@gen-lang-client-0462704292.iam.gserviceaccount.com
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  admin-panel:
    build: ./packages/admin-panel
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - SERVER_API_URL=http://server:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
